### ISSUE TITLE
Failed to run (Training Colab)

### ISSUE THREAD

**Issue by skilomlg** [very-strange-developer/VITS_ColabNotebooks#3]
I get this error when using the colab. It's really annoying and I got the same error from other parts of the colab.

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6006 (pid 966), started 0:00:59 ago. (Use '!kill 966' to kill it.)

  ```
File "/content/vits/monotonic_align/__init__.py", line 1
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```

Also what does this mean? 
```
/content/drive/My Drive/colab/outdir/elvis/G_0.pth

/content/vits/utils.py:134: WavFileWarning: Chunk (non-data) not understood, skipping it.
  sampling_rate, data = read(full_path)
/content/vits/utils.py:134: WavFileWarning: Chunk (non-data) not understood, skipping it.
  sampling_rate, data = read(full_path)
/usr/local/lib/python3.7/dist-packages/torch/functional.py:573: UserWarning: stft will soon require the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release. (Triggered internally at  ../aten/src/ATen/native/SpectralOps.cpp:659.)
  normalized, onesided, return_complex)
/usr/local/lib/python3.7/dist-packages/torch/functional.py:573: UserWarning: stft will soon require the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release. (Triggered internally at  ../aten/src/ATen/native/SpectralOps.cpp:659.)
  normalized, onesided, return_complex)

---------------------------------------------------------------------------

KeyError                                  Traceback (most recent call last)

[<ipython-input-9-e9a99d97dd4b>](https://localhost:8080/#) in <module>()
    290 
    291 if __name__ == "__main__":
--> 292   main()

6 frames

[/usr/local/lib/python3.7/dist-packages/torch/_utils.py](https://localhost:8080/#) in reraise(self)
    432             # instantiate since we don't know how to
    433             raise RuntimeError(msg) from None
--> 434         raise exception
    435 
    436 

KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/vits/data_utils.py", line 94, in __getitem__
    return self.get_audio_text_pair(self.audiopaths_and_text[index])
  File "/content/vits/data_utils.py", line 61, in get_audio_text_pair
    text = self.get_text(text)
  File "/content/vits/data_utils.py", line 85, in get_text
    text_norm = cleaned_text_to_sequence(text)
  File "/content/vits/text/__init__.py", line 35, in cleaned_text_to_sequence
    sequence = [_symbol_to_id[symbol] for symbol in cleaned_text]
  File "/content/vits/text/__init__.py", line 35, in <listcomp>
    sequence = [_symbol_to_id[symbol] for symbol in cleaned_text]
KeyError: '’'
```
Am I doing something wrong?

**Comment by very-strange-developer** [comment]
I think you should modify "symbols.py".
Symbols that are not in "symbols.py" may be in your subscripts.
Also, you have another method to solving an error. change ’ -> ' .

**Comment by very-strange-developer** [comment]
And I'll upload english version of this notebook(may contains a little of typo or sentence error) on this weekend.
thank you.

**Comment by skilomlg** [comment]
Ok, No problem. 



> I think you should modify "symbols.py". Symbols that are not in "symbols.py" may be in your subscripts. Also, you have another method to solving an error. change ’ -> ' .

But I'm not a programmer so I don't have much knowledge with code. I have no idea how to modify symbols.py. But I'll try.

**Comment by very-strange-developer** [comment]
To change subscripts, you can solve this error without modifying codes.
change ’ to ' in the subscripts.

**Comment by very-strange-developer** [comment]
I recommend changing the subscripts rather than changing the code.

**Comment by skilomlg** [comment]
Okay

**Comment by skilomlg** [comment]
Sorry but I'm not understanding what the subscript is. I'm confused.

**Comment by very-strange-developer** [comment]
I can not guess the name of this part : 'filename'|'here'<--
Quote? or Dialogue? or Subtitle?

The word 'subscript' what I mentioned was this. 'filename'|'here'<--

**Comment by skilomlg** [comment]
```
wavs/1.wav|Let’s go to the beach let’s go get a wave.
wavs/2.wav|They say what they gonna say, have a drink clink found a bright light.
wavs/3.wav|Bad bitches like me it’s hard to come by. 
wavs/4.wav|Is it two three leave a good tip, I’ma blow out my money. 
wavs/5.wav|Jump in my hoopty, hoopty, hoop, I own that.
wavs/6.wav|And I ain't paying my rent this month, I owe that.
wavs/7.wav|But fuck who you want and fuck who you like.
wavs/8.wav|Dancehall life, there's no end in sight.
wavs/9.wav|And everybody, let me hear you say ray, ray, ray.
wavs/10.wav|Spend all your money 'cause today payday.
wavs/11.wav|You're a G, you a G, G, G.
wavs/12.wav|Ay yo, tonight is the night that I’ma get twisted.
wavs/13.wav|Mix Moscato and vodka, I'ma mix it.
wavs/14.wav|Roll that spaceship, we about to get lifted.
wavs/15.wav|Live in the present, that gift is for the gifted.
wavs/16.wav|This what you came, this what you came for you get what you buy, this what you paid for.
wavs/17.wav|So make sure the stars is what you aim for, make mistakes though.
wavs/18.wav|Drinks on you or the drinks is on me.
wavs/19.wav|We ain't going nowhere like tanks is on E.
wavs/20.wav|We still getting money, which bank is it gonna be, If he sexy, he planking on me.
wavs/21.wav|Boys want all of that tell the bartender, say my order that.
wavs/22.wav|It's bottle service, he ordered that might let him take it home and slaughter that.
wavs/23.wav|He got friends for all of my friends they ain't leaving 'til we say when.
wavs/24.wav|And we gon' hangover the next day but we will remember this day.
wavs/25.wav|So drop the pop and get low or we can drop the top and just cruise.
wavs/26.wav|We fresh to death, down to the shoes my only motto in life.
wavs/27.wav|This one is for the boys with the boomer system.
wavs/28.wav|Top down AC with the cooling system, When he come up in the club he be blazing up.
wavs/29.wav|Got stacks on deck like he’s saving up.
wavs/30.wav|And he ill, he real, he might gotta deal.
wavs/31.wav|He pop bottles and he got the right kind of build he cold, he dope, he might sell.
wavs/32.wav|Drip, Drip sailor of the ship, ship when he make it drip, drip kiss him on the lip, lip.
wavs/33.wav|That’s the kinda dude I was looking for.
wavs/34.wav|And yes you get slapped if your looking.
wavs/35.wav|I said, excuse me you're a hell of a guy, I mean my, my, my, my you're like pelican fly.
wavs/36.wav|You're so shy and I'm loving your tie, You're like slicker than the guy with the thing on his eye, oh.
wavs/37.wav|Yes I did, yes I did somebody please tell him who the eff I is.
wavs/38.wav|I am Nicki Minaj, I mack them dudes up, that coupes up.
wavs/39.wav|He just gotta give me that look when he give me that look.
wavs/40.wav|Excuse me, you're a hell of a guy you know. I really got a thing for American guys I mean, sigh.
wavs/41.wav|Sickening eyes I can tell that you're in touch with your feminine side.
wavs/42.wav|It was back in 07 did a couple of tapes.
wavs/43.wav|Did a couple DVDs made a couple mistakes.
wavs/44.wav|Didn't know what I was doing but I put on a cape.
wavs/45.wav|You told me I would lose but I won.
wavs/46.wav|I might cop a million Jimmy Choo's just for fun.
wavs/47.wav|Got the eye of the tiger.
wavs/48.wav|Now it's me and my time it's just me in my prime.
wavs/49.wav|Everything I tried to teach 'em they gone see it in time.
wavs/50.wav|Tell them bitches get a stick, I'm done leading the blind.
wavs/51.wav|Got two shows tonight that's Brooklyn and Dallas then a private party at the Buckingham palace.
wavs/52.wav|That's young money, cash money, yeah, I'm universal.
wavs/53.wav|Buy my mother a couch now I'm sitting at the closing, bought my mother a house.
wavs/54.wav|You could never understand why I grind like I do.
wavs/55.wav|Cause even when my daddy was on crack.
wavs/56.wav|You ain't gotta skip a track.
wavs/57.wav|I ain't gotta get awards I just walk up out the door.
wavs/58.wav|All the girls will commend.
wavs/59.wav|As long as they understand that I'm fighting for the girls.
wavs/60.wav|Before they could begin you told them it was the end, But I am here to.
wavs/61.wav|Reverse the curse that they live in.
wavs/62.wav|I'm a only choose one, you might get addressed on the second album.
wavs/63.wav|Til I mother fucking say so.
wavs/64.wav|And I'm a go and get some bibs for 'em.
wavs/65.wav|A couple formulas, little pretty lids on.
wavs/66.wav|If I had a dick I would pull it out and piss on ‘em.
wavs/67.wav|Let me shake it off.
wavs/68.wav|I just signed a couple deals I might break you off.
wavs/69.wav|And we ain't making up, I don't need a mediator.
wavs/70.wav|I keep shooters up top.
wavs/71.wav|She ain’t a Nicki fan.
wavs/72.wav|And I ain't talking 'bout Phoenix.
wavs/73.wav|I get money so I do.
wavs/74.wav|Couple wet wipes in case a bum try to touch me.
wavs/75.wav|I'm the terminator.
wavs/76.wav|Talk slick, I'm a have to terminate her.
wavs/77.wav|You my seed, I spray you with a germinator.
wavs/78.wav|If you could turn back time, Cher, You used to be here, now you're gone near.
wavs/79.wav|You let me win you let me ride.
wavs/80.wav|You let me rock, You let me slide.
wavs/81.wav|And when they looking you let me hide.
wavs/82.wav|I always hated but looking back.
wavs/83.wav|It made me greater, You always told me forget the haters.
wavs/84.wav|Just get my money, Just get my waiter, Know when I’m lying. 
wavs/85.wav|What am I trying, No you ain’t lying I try to fight it.
wavs/86.wav|You make me laugh you make me horse.
wavs/87.wav|From yelling at you, and getting at you, picking them dishes throwing them at you.
wavs/88.wav|Can you see through me ‘cause you say Nicki.
wavs/89.wav|Then I say screw you and you start dressing and you start leaving.
wavs/90.wav|And I start crying and I start screaming the heavy breathing.
wavs/91.wav|Answer this question class is in session.
wavs/92.wav|Control my mind capture my soul.
wavs/93.wav|Okay you’re right just let it go.
wavs/94.wav|Maybe that’ll make the pain go away.
wavs/95.wav|Trying to forgive you for abandoning me.
wavs/96.wav|Praying but I think I’m still an angel away.
wavs/97.wav|Angel away, yeah strange that way, maybe that’s why I chase strangers that way.
wavs/98.wav|They got them guns out aiming at me, But I’ll be come near when they aiming at me.
wavs/99.wav|Everybody wanna try to box me in.
wavs/100.wav|Suffocating every time it locks me in.
wavs/101.wav|Painting their own pictures then they crop me in.
wavs/102.wav|But I will remain where the top begins.
wavs/103.wav|’Cause I am not a word, I am not a line.
wavs/104.wav|I am not a girl that can ever be defined.
wavs/105.wav|I am not fly, I’m levitation, I represent an entire generation.
wavs/106.wav|I hear the criticism loud and clear, That is how I know that the time is near.
wavs/107.wav|Come alive in the time of fear, And I ain’t got no mother fucking time to.
wavs/108.wav|I fly with the stars in the skies, I’m am no longer trying to survive.
wavs/109.wav|I believe that life is a prize.
wavs/110.wav|And who I fire, I get what I desire, It’s my empire.
wavs/111.wav|And yes I call the shots, I am the umpire. 
wavs/112.wav|I sprinkle holy water upon the vampire.
wavs/113.wav|In this very moment I’m king, In this very moment I slayed the life with a sling.
wavs/114.wav|That I will retire with the ring and I will retire with the crown.
wavs/115.wav|Yes, No I’m not lucky I’m blessed.
wavs/116.wav|Yes, clap for the heavy weight champ me.
wavs/117.wav|But I couldn’t do it all alone.
wavs/118.wav|’Cause I’m still hood how he would couldn’t change me.
wavs/119.wav|Shout out to my haters, sorry that you couldn’t phase me.
wavs/120.wav|Put your drinks up, It’s a celebration.
```
This is my transcribed filelist for my Nicki Minaj Dataset for TacoTron2. What do I need to change here to make it work on vits? or for the colab?

**Comment by very-strange-developer** [comment]
wavs/1.wav|Let's go to the beach let's go get a wave.
wavs/2.wav|They say what they gonna say, have a drink clink found a bright light.
wavs/3.wav|Bad bitches like me it's hard to come by. 
wavs/4.wav|Is it two three leave a good tip, I'ma blow out my money. 
wavs/5.wav|Jump in my hoopty, hoopty, hoop, I own that.
wavs/6.wav|And I ain't paying my rent this month, I owe that.
wavs/7.wav|But fuck who you want and fuck who you like.
wavs/8.wav|Dancehall life, there's no end in sight.
wavs/9.wav|And everybody, let me hear you say ray, ray, ray.
wavs/10.wav|Spend all your money 'cause today payday.
wavs/11.wav|You're a G, you a G, G, G.
wavs/12.wav|Ay yo, tonight is the night that I'ma get twisted.
wavs/13.wav|Mix Moscato and vodka, I'ma mix it.
wavs/14.wav|Roll that spaceship, we about to get lifted.
wavs/15.wav|Live in the present, that gift is for the gifted.
wavs/16.wav|This what you came, this what you came for you get what you buy, this what you paid for.
wavs/17.wav|So make sure the stars is what you aim for, make mistakes though.
wavs/18.wav|Drinks on you or the drinks is on me.
wavs/19.wav|We ain't going nowhere like tanks is on E.
wavs/20.wav|We still getting money, which bank is it gonna be, If he sexy, he planking on me.
wavs/21.wav|Boys want all of that tell the bartender, say my order that.
wavs/22.wav|It's bottle service, he ordered that might let him take it home and slaughter that.
wavs/23.wav|He got friends for all of my friends they ain't leaving 'til we say when.
wavs/24.wav|And we gon' hangover the next day but we will remember this day.
wavs/25.wav|So drop the pop and get low or we can drop the top and just cruise.
wavs/26.wav|We fresh to death, down to the shoes my only motto in life.
wavs/27.wav|This one is for the boys with the boomer system.
wavs/28.wav|Top down AC with the cooling system, When he come up in the club he be blazing up.
wavs/29.wav|Got stacks on deck like he's saving up.
wavs/30.wav|And he ill, he real, he might gotta deal.
wavs/31.wav|He pop bottles and he got the right kind of build he cold, he dope, he might sell.
wavs/32.wav|Drip, Drip sailor of the ship, ship when he make it drip, drip kiss him on the lip, lip.
wavs/33.wav|That's the kinda dude I was looking for.
wavs/34.wav|And yes you get slapped if your looking.
wavs/35.wav|I said, excuse me you're a hell of a guy, I mean my, my, my, my you're like pelican fly.
wavs/36.wav|You're so shy and I'm loving your tie, You're like slicker than the guy with the thing on his eye, oh.
wavs/37.wav|Yes I did, yes I did somebody please tell him who the eff I is.
wavs/38.wav|I am Nicki Minaj, I mack them dudes up, that coupes up.
wavs/39.wav|He just gotta give me that look when he give me that look.
wavs/40.wav|Excuse me, you're a hell of a guy you know. I really got a thing for American guys I mean, sigh.
wavs/41.wav|Sickening eyes I can tell that you're in touch with your feminine side.
wavs/42.wav|It was back in 07 did a couple of tapes.
wavs/43.wav|Did a couple DVDs made a couple mistakes.
wavs/44.wav|Didn't know what I was doing but I put on a cape.
wavs/45.wav|You told me I would lose but I won.
wavs/46.wav|I might cop a million Jimmy Choo's just for fun.
wavs/47.wav|Got the eye of the tiger.
wavs/48.wav|Now it's me and my time it's just me in my prime.
wavs/49.wav|Everything I tried to teach 'em they gone see it in time.
wavs/50.wav|Tell them bitches get a stick, I'm done leading the blind.
wavs/51.wav|Got two shows tonight that's Brooklyn and Dallas then a private party at the Buckingham palace.
wavs/52.wav|That's young money, cash money, yeah, I'm universal.
wavs/53.wav|Buy my mother a couch now I'm sitting at the closing, bought my mother a house.
wavs/54.wav|You could never understand why I grind like I do.
wavs/55.wav|Cause even when my daddy was on crack.
wavs/56.wav|You ain't gotta skip a track.
wavs/57.wav|I ain't gotta get awards I just walk up out the door.
wavs/58.wav|All the girls will commend.
wavs/59.wav|As long as they understand that I'm fighting for the girls.
wavs/60.wav|Before they could begin you told them it was the end, But I am here to.
wavs/61.wav|Reverse the curse that they live in.
wavs/62.wav|I'm a only choose one, you might get addressed on the second album.
wavs/63.wav|Til I mother fucking say so.
wavs/64.wav|And I'm a go and get some bibs for 'em.
wavs/65.wav|A couple formulas, little pretty lids on.
wavs/66.wav|If I had a dick I would pull it out and piss on ‘em.
wavs/67.wav|Let me shake it off.
wavs/68.wav|I just signed a couple deals I might break you off.
wavs/69.wav|And we ain't making up, I don't need a mediator.
wavs/70.wav|I keep shooters up top.
wavs/71.wav|She ain't a Nicki fan.
wavs/72.wav|And I ain't talking 'bout Phoenix.
wavs/73.wav|I get money so I do.
wavs/74.wav|Couple wet wipes in case a bum try to touch me.
wavs/75.wav|I'm the terminator.
wavs/76.wav|Talk slick, I'm a have to terminate her.
wavs/77.wav|You my seed, I spray you with a germinator.
wavs/78.wav|If you could turn back time, Cher, You used to be here, now you're gone near.
wavs/79.wav|You let me win you let me ride.
wavs/80.wav|You let me rock, You let me slide.
wavs/81.wav|And when they looking you let me hide.
wavs/82.wav|I always hated but looking back.
wavs/83.wav|It made me greater, You always told me forget the haters.
wavs/84.wav|Just get my money, Just get my waiter, Know when I'm lying. 
wavs/85.wav|What am I trying, No you ain't lying I try to fight it.
wavs/86.wav|You make me laugh you make me horse.
wavs/87.wav|From yelling at you, and getting at you, picking them dishes throwing them at you.
wavs/88.wav|Can you see through me ‘cause you say Nicki.
wavs/89.wav|Then I say screw you and you start dressing and you start leaving.
wavs/90.wav|And I start crying and I start screaming the heavy breathing.
wavs/91.wav|Answer this question class is in session.
wavs/92.wav|Control my mind capture my soul.
wavs/93.wav|Okay you're right just let it go.
wavs/94.wav|Maybe that'll make the pain go away.
wavs/95.wav|Trying to forgive you for abandoning me.
wavs/96.wav|Praying but I think I'm still an angel away.
wavs/97.wav|Angel away, yeah strange that way, maybe that's why I chase strangers that way.
wavs/98.wav|They got them guns out aiming at me, But I'll be come near when they aiming at me.
wavs/99.wav|Everybody wanna try to box me in.
wavs/100.wav|Suffocating every time it locks me in.
wavs/101.wav|Painting their own pictures then they crop me in.
wavs/102.wav|But I will remain where the top begins.
wavs/103.wav|'Cause I am not a word, I am not a line.
wavs/104.wav|I am not a girl that can ever be defined.
wavs/105.wav|I am not fly, I'm levitation, I represent an entire generation.
wavs/106.wav|I hear the criticism loud and clear, That is how I know that the time is near.
wavs/107.wav|Come alive in the time of fear, And I ain't got no mother fucking time to.
wavs/108.wav|I fly with the stars in the skies, I'm am no longer trying to survive.
wavs/109.wav|I believe that life is a prize.
wavs/110.wav|And who I fire, I get what I desire, It's my empire.
wavs/111.wav|And yes I call the shots, I am the umpire. 
wavs/112.wav|I sprinkle holy water upon the vampire.
wavs/113.wav|In this very moment I'm king, In this very moment I slayed the life with a sling.
wavs/114.wav|That I will retire with the ring and I will retire with the crown.
wavs/115.wav|Yes, No I'm not lucky I'm blessed.
wavs/116.wav|Yes, clap for the heavy weight champ me.
wavs/117.wav|But I couldn't do it all alone.
wavs/118.wav|'Cause I'm still hood how he would couldn't change me.
wavs/119.wav|Shout out to my haters, sorry that you couldn't phase me.
wavs/120.wav|Put your drinks up, It's a celebration.

**Comment by very-strange-developer** [comment]
↑ This transcription is likely to work.

**Comment by skilomlg** [comment]
Ok Thank you.

**Comment by skilomlg** [comment]
Have you ever tested the colab or ever got it working?

**Comment by very-strange-developer** [comment]
Yes it works.

here is training result of my custom dataset :
https://colab.research.google.com/drive/1r1fBChDQbVcRVLV1oNq2y3c3B_9TKyAq?usp=sharing

**Comment by very-strange-developer** [comment]
Also, you can not train with Tesla K80.
Restart runtime repeatedly to be assigned GPUs such as Tesla T4.

**Comment by skilomlg** [comment]
P100 doesn't work? I always get assigned a P100.

**Comment by skilomlg** [comment]
Just checked out the English Colab, It seems to be working. Thank you so much.

**Comment by skilomlg** [comment]
It's not working, I trained my model over night and it's giving me an out of range error when I try to synthesize it. 

```
IndexError                                Traceback (most recent call last)

[<ipython-input-2-b06d6e95dc66>](https://localhost:8080/#) in <module>()
     27 download_setup_py("1zWT38kZ6usACkYLl_36n_qJJruPz-kUE","/content/vits/layers.py")
     28 download_setup_py("1EkAfQdRpXOd4HThVpTUwrsKzQCYo8N9n","/content/vits/stft.py")
---> 29 download_setup_py(yourmodel,"/content/vits/G_0.pth")
     30 if your_symbols_py != "":
     31   download_setup_py(your_symbols_py,"/content/vits/text/symbols.py")

[<ipython-input-2-b06d6e95dc66>](https://localhost:8080/#) in download_setup_py(file_id, file_name)
     19   get_ipython().system('curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id={file_id}" > /dev/null')
     20   confirm_text = get_ipython().getoutput("awk '/download/ {print $NF}' ./cookie")
---> 21   confirm_text = confirm_text[0]
     22   get_ipython().system('curl -Lb ./cookie "https://drive.google.com/uc?export=download&confirm={confirm_text}&id={file_id}" -o {file_name}')
     23 

IndexError: list index out of range
```

And when i try using the vits Demo Colab I get this. 

```
---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-14-cef58ad51c85> in <module>()
      6 _ = net_g.eval()
      7 
----> 8 _ = utils.load_checkpoint("G_0.pth", net_g, None)

1 frames

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
   1043         if len(error_msgs) > 0:
   1044             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
-> 1045                                self.__class__.__name__, "\n\t".join(error_msgs)))
   1046         return _IncompatibleKeys(missing_keys, unexpected_keys)
   1047 

RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
	size mismatch for enc_p.emb.weight: copying a param with shape torch.Size([183, 192]) from checkpoint, the shape in current model is torch.Size([178, 192]).
```
